### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by StachuDotNet** [kunjee17/kunjee17.github.io#1]
Hi there.
I'd like to send a PR for minor wording changes, but I'm not sure the best way to do that. Having some instructions in the README.md would be great :)

I see source `.md` files in `/content/post`.
As such, my assumption is that your process is:
* edit/add .md files
* ??? magic build step
* push 

I've determined that you're using "Hugo."
So, I installed it and then tried to run `hugo` at the root directory.
This resulted in many minor changes like this:
![image](https://user-images.githubusercontent.com/906686/45256497-057dcf00-b365-11e8-99d9-41cb38afe8ce.png)

So, I'm guessing that you're tied to a specific Hugo version but I'm sure which.

Please advise :)

**Comment by kunjee17** [comment]
Oh sorry. I'm using latest hugo. So, build step is as simple as `hugo` . And while writing you can use `hugo server -w`. 

Don't worry about minor changes. It happens everytime. 

Or there is one more option. Just give PR for MD files and I'll build on my machine.
